### ISSUE TITLE
[feature-requet] Validation errors

### ISSUE THREAD

**Issue by erdostom** [kumailht/gridforms#34]
I know this is part of the TODO list, and I just wanted to vote that it go on top of the queue. It would really be awesome if there were a place and styling to display any errors that field-specific.

Domo arigato

**Comment by djanowski** [comment]
Any news?

**Comment by kmanley** [comment]
I notice there's a port at https://github.com/herrhelms/meteor-gridforms which augments the CSS with some styling for errors, perhaps it could be adapted here.

**Comment by zepernick** [comment]
For anyone wanting to add the validation on their own based on metero-gridforms:

Add this css to the style sheet
```css
.grid-form [data-row-span] [data-field-span].grid-form-error.focus {	background: #fffad4; cursor: text; }
.grid-form [data-row-span] [data-field-span].grid-form-error, .grid-form [data-row-span] [data-field-span].grid-form-error:hover { background: #FE826D }
.grid-form .grid-form-help { font-size:75%; margin:-5px 0; color:rgba(33,33,33,.45); -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; -o-user-select: none; user-select: none;    }
```

Add this markup to the field when adding a validation error
```html
        <div data-row-span="1">
            <div data-field-span="1" class="grid-form-error">
                <label>Field 1</label>
                <input type="text">
                <span class="grid-form-help">Required Field </span>
            </div>
        </div>
```
